### PR TITLE
Mass signal in MQTT bridge using templates

### PR DESCRIPTION
**Pull request by magni-mar**
This is a stacked PR upon these:  #428  #429 . So when those are merged some of these files will disappear.

AVEVA seemingly doesn't support templating types, however, more information on this subject might be necessary to fully conclude this.

### CODE REVIEW

**Comment by magni-mar** [comment]
> This is a stacked PR upon these: #428 #429 . So when those are merged some of these files will disappear.
> 
> AVEVA seemingly doesn't support templating types, however, more information on this subject might be necessary to fully conclude this.

AVEVA does support this with very specific parameters for topic names, implemented but yet to be tested.

**Comment by magni-mar** [comment]
AVEVA doesn´t understand the NBIRTH and provides no error logs to debug why.

**Comment by jbbjarnason** [comment]
@magni-mar should we change this to an issue and reference this PR? Seems like it does not work on Aveva side?

**Comment by magni-mar** [comment]
> @magni-mar should we change this to an issue and reference this PR? Seems like it does not work on Aveva side?

Sounds good, I don't see the need for this as of now.

**Comment by jbbjarnason** [comment]
Changed to an issue

**Pull request closed without merging**
